[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    pololu/QTRSensors @ ^4.0.0
    adafruit/Adafruit TCS34725 @ ^1.4.2
    adafruit/Adafruit BusIO @ ^1.14.0
    robtillaart/AS5600 @ ^0.6.0
    robtillaart/TCA9548 @ ^0.2.0
    upload_protocol = esptool
board_build.flash_mode = dio